services:
  - type: web
    name: doc-chatbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: MISTRAL_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
